### PR TITLE
Upgrade Button Styling  Fix

### PR DESCRIPTION
**Pull request by Koustavd18**
The Upgrade to latest version in about modal was distorted. This PR aligns the styling of that button

### CODE REVIEW

**Comment by Koustavd18** [comment]
Screenshot 2024-08-22 at 9 23 50 AM

**Comment by Koustavd18** [comment]
@balaji-jr  the changes are from line 112

**Review by balaji-jr — DISMISSED** [review]
Make sure to remove the hard-coded part after testing

**Review by nikhilsinhaparseable — DISMISSED** [review]
looks good to me
Screenshot 2024-08-22 at 5 56 11 PM

**Pull request merged**
