### PR TITLE
Add PropTypes to shared components

### LINKED ISSUE #37: Add PropTypes to shared components

### PR DESCRIPTION
**Pull request by Aksa12**
Closes #37

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks for the PR @Aksa12 . cc @ameen4455 can you please take a look

**Comment by ameen4455** [comment]
@Aksa12 could you please take a look at the issues detected by DeepSource for this PR?

**Comment by Aksa12** [comment]
@ameen4455 yeah, looking into it.

**Comment by Aksa12** [comment]
@ameen4455 DeepSource issues resolved. You can review the PR.

**Comment by ameen4455** [comment]
@Aksa12 will check, thank you!

**Review by ameen4455 — APPROVED** [review]

**Review by ameen4455 — APPROVED** [review]

**Pull request merged**
