### PR TITLE
Home Screen-Loading & error state fixes (#347)

### PR DESCRIPTION
**Pull request by praveen5959**
Fixes https://github.com/parseablehq/console/issues/347

### CODE REVIEW

**Review by balaji-jr — CHANGES_REQUESTED** [review]
Everything looks good.  
1. Use this for loading state: https://github.com/balaji-jr/forked-console/blob/prettier-workflow-fix/src/pages/Stream/Views/Explore/LoadingViews.tsx#L35
2. The shadow is not visible on my mac. Lets add a static border like this and rm the scrolled logic and shadow.  
Screenshot 2024-10-28 at 9 45 56 AM

**Review by balaji-jr — CHANGES_REQUESTED** [review]
The loader needs to be at the center of the page

**Review by balaji-jr — CHANGES_REQUESTED** [review]
Screenshot 2024-10-28 at 9 38 39 AM
Now the padding's gone at the bottom.

**Comment by praveen5959** [comment]
> Screenshot 2024-10-28 at 12 14 55 PM
> Now the padding's gone at the bottom.

@balaji-jr  Have fixed this: https://console-private-34uh8zd88-praveen-k-bs-projects.vercel.app/

**Review by balaji-jr — APPROVED** [review]

**Pull request merged**
