### PR TITLE
ISSUE-176 - conditionally hide live tail for https protocol

### PR DESCRIPTION
**Pull request by balaji-jr**
Temporary patch for #176 
Similar issue: https://stackoverflow.com/questions/67078147/struggling-to-make-grpc-web-and-https-work

### CODE REVIEW

**Comment by nitisht** [comment]
@balaji-jr can you sign the CLA by adding the comment.

**Comment by balaji-jr** [comment]
recheck

**Review by nitisht — APPROVED** [review]
LGTM & Tested

**Review by nikhilsinhacloudsurfex — APPROVED** [review]
tested the livetail on http, looks good

**Comment by nativ-labs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nativ-labs** [comment]
recheck

**Pull request merged**
