### PR TITLE
update roles in create user modal if new role created

### PR DESCRIPTION
**Pull request by aixart12**
- "Create User Modal " : disabled the create  button if password is created 
- update the role in create user modal if user add new role
- change the create role modal title

### CODE REVIEW

**Comment by aixart12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aixart12** [comment]
#180

**Review by nikhilsinhacloudsurfex — APPROVED** [review]
tested all three fixes, looks good

**Comment by aixart12** [comment]
closing due to  pushed with non personal git-hub account

**Pull request closed without merging**
