### PR TITLE
fix prettier workflow git config

### PR DESCRIPTION
**Pull request by balaji-jr**

### CODE REVIEW

**Review by nitisht — COMMENTED** [review]
Can you change the `Checkout` step to 

```yaml
      - name: Checkout
        uses: actions/checkout@v3
```

Don't think we need `with`. Refer: https://github.com/parseablehq/parseable/blob/main/.github/workflows/integration-test.yaml#L17-L18

**Comment by balaji-jr** [comment]
> Can you change the `Checkout` step to
> 
> ```yaml
>       - name: Checkout
>         uses: actions/checkout@v3
> ```
> 
> Don't think we need `with`. Refer: https://github.com/parseablehq/parseable/blob/main/.github/workflows/integration-test.yaml#L17-L18

Done.

**Comment by nitisht** [comment]
Write permission would be good for the action so it automatically fixes the issue right?

**Comment by balaji-jr** [comment]
> Write permission would be good for the action so it automatically fixes the issue right?
I have added it again.

**Comment by nitisht** [comment]
so it needs the branch as well..guess will have to add the previous with section also. just need to see why it was failing

**Pull request closed without merging**
